# Generated by Django 5.2 on 2025-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='state',
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('bozza_pronta', 'Bozza Pronta'), ('bozza_rifiutata', 'Bozza Rifiutata'), ('bozza_valida', 'Bozza Valida'), ('validata', 'Validata'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validata', 'Validata'), ('rifiutata', 'rifiutata')], default='bozza', max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('amministratore', 'Amministratore'), ('copywriter', 'Copywriter'), ('approvatore', 'Approvatore'), ('validatore_lingua', 'ValidatoreLingua'), ('publisher', 'Publisher')], default='copywriter', max_length=20),
        ),
    ]
