# Generated by Django 5.2 on 2025-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_content_state_content_status_language_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='keywords',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='tone_voice',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validata', 'Validata'), ('rifiutata', 'rifiutata')], default='pending', max_length=50),
        ),
    ]
