# Generated by Django 5.2 on 2025-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_content_image_content_keywords_content_tone_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='tone_voice',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
