# Generated by Django 5.2 on 2025-04-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_content_keywords_alter_content_tone_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='titolo esempio', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='languages',
            field=models.ManyToManyField(blank=True, to='api.language'),
        ),
    ]
