# Generated by Django 5.2 on 2025-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_content_title_alter_content_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
