# Generated by Django 5.2 on 2025-04-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='status',
        ),
        migrations.RemoveField(
            model_name='language',
            name='text',
        ),
        migrations.CreateModel(
            name='LanguageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validata', 'Validata'), ('rifiutata', 'rifiutata')], default='pending', max_length=50)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.content')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.language')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content', 'language'), name='unique_content_language')],
            },
        ),
    ]
