# Generated by Django 5.2 on 2025-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_language_status_remove_language_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('bozza_pronta', 'Bozza Pronta'), ('bozza_rifiutata', 'Bozza Rifiutata'), ('bozza_valida', 'Bozza Valida'), ('traduzione_rifiutata', 'traduzione rifiutata'), ('validata', 'Validata'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=50),
        ),
    ]
