# Generated by Django 5.2 on 2025-04-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lang',
            field=models.CharField(choices=[('it', 'Italian'), ('en', 'English'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish')], default='it', max_length=2),
        ),
    ]
