# Generated by Django 5.2 on 2025-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_content_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagetranslation',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
