# Generated by Django 5.2 on 2025-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_languagetranslation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('amministratore', 'Amministratore'), ('copywriter', 'Copywriter'), ('approvatore', 'Approvatore'), ('traduttore', 'Traduttore'), ('publisher', 'Publisher')], default='copywriter', max_length=20),
        ),
    ]
