# Generated by Django 5.2 on 2025-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('bozza_pronta', 'Bozza Pronta'), ('bozza_rifiutata', 'Bozza Rifiutata'), ('bozza_validata', 'Bozza Validata'), ('traduzione_rifiutata', 'traduzione rifiutata'), ('validata', 'Validata'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=50),
        ),
    ]
