# Generated by Django 5.2 on 2025-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_content_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='languages',
            new_name='langs',
        ),
        migrations.AddField(
            model_name='customuser',
            name='langs',
            field=models.ManyToManyField(blank=True, to='api.language'),
        ),
    ]
