# Generated by Django 5.2 on 2025-05-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_languages_content_langs_customuser_langs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageTranslation',
            new_name='LangTranslation',
        ),
    ]
