# Generated by Django 5.2 on 2025-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_languagetranslation_langtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='custom_prompt',
            field=models.TextField(blank=True),
        ),
    ]
