# Generated by Django 5.2 on 2025-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='rejection_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='langtranslation',
            name='rejection_message',
            field=models.TextField(blank=True),
        ),
    ]
