# Generated by Django 5.2 on 2025-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_content_rejection_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('bozza_rifiutata', 'Bozza Rifiutata'), ('bozza_validata', 'Bozza Validata'), ('review_traduzioni', 'Review Traduzioni'), ('validata', 'Validata'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=50),
        ),
    ]
