# Generated by Django 5.2 on 2025-05-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_content_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='lang',
        ),
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='api.language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
