# Generated by Django 5.2 on 2025-05-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_content_lang_content_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='llm',
            field=models.CharField(choices=[('gpt', 'gpt'), ('claude_sonnet', 'claude_sonnet'), ('deepseek', 'deepseek'), ('llama', 'llama')], default='gpt', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='api.language'),
            preserve_default=False,
        ),
    ]
