# Generated by Django 5.2 on 2025-05-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_content_llm_alter_content_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.AddField(
            model_name='content',
            name='file1_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
