# Generated by Django 5.2 on 2025-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_content_image_content_file1_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('review', 'review'), ('bozza_rifiutata', 'Bozza Rifiutata'), ('bozza_validata', 'Bozza Validata'), ('review_traduzioni', 'Review Traduzioni'), ('validata', 'Validata'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=50),
        ),
    ]
