# Generated by Django 5.2 on 2025-05-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_contentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file1_url',
        ),
    ]
