# Generated by Django 5.2 on 2025-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_content_file1_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'guest'), ('amministratore', 'Amministratore'), ('copywriter', 'Copywriter'), ('approvatore', 'Approvatore'), ('traduttore', 'Traduttore'), ('publisher', 'Publisher')], default='guest', max_length=20),
        ),
    ]
