# Generated by Django 5.2 on 2025-06-02 09:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_llmmodel_llmservice_remove_content_llm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='llmmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.llmmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalContent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('tone_voice', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('custom_prompt', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('bozza', 'Bozza'), ('review', 'review'), ('bozza_rifiutata', 'Bozza Rifiutata'), ('bozza_validata', 'Bozza Validata'), ('review_traduzioni', 'Review Traduzioni'), ('validata', 'Validata'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=50)),
                ('rejection_message', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.contenttype')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.language')),
                ('llmmodel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.llmmodel')),
            ],
            options={
                'verbose_name': 'historical content',
                'verbose_name_plural': 'historical contents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
