# Generated by Django 5.2 on 2025-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_historicalcontentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='s3files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='s3files',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
