# Generated by Django 5.2 on 2025-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_content_s3files_historicalcontent_s3files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='s3files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontent',
            name='s3files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
