# Generated by Django 5.2 on 2025-06-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_content_s3files_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalContentFile',
        ),
    ]
