# Generated by Django 5.2 on 2025-06-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_contenttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='state',
            field=models.CharField(choices=[('local', 'local'), ('sent', 'sent'), ('received', 'received'), ('pending', 'pending'), ('failed', 'failed'), ('success', 'success')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='state',
            field=models.CharField(choices=[('local', 'local'), ('sent', 'sent'), ('received', 'received'), ('pending', 'pending'), ('failed', 'failed'), ('success', 'success')], default='local', max_length=20),
        ),
    ]
