# Generated by Django 5.2 on 2025-06-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_content_state_historicalcontent_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontent',
            name='state',
        ),
    ]
