# Generated by Django 5.2 on 2025-06-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_historicalcontent_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='llm_input',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='llm_output',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='llm_input',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='llm_output',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
