# Generated by Django 5.2 on 2025-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_content_llm_input_content_llm_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='llm_input',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='llm_output',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontent',
            name='llm_input',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontent',
            name='llm_output',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
