# Generated by Django 5.2 on 2025-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_content_llm_input_alter_content_llm_output_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='llm_input',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='historicalcontent',
            old_name='llm_input',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='content',
            name='llm_output',
        ),
        migrations.RemoveField(
            model_name='historicalcontent',
            name='llm_output',
        ),
        migrations.AddField(
            model_name='langtranslation',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='langtranslation',
            name='state',
            field=models.CharField(choices=[('local', 'local'), ('sent', 'sent'), ('received', 'received'), ('pending', 'pending'), ('failed', 'failed'), ('success', 'success')], default='local', max_length=20),
        ),
    ]
