# Generated by Django 5.2 on 2025-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_llm_input_content_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='state_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='state_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='langtranslation',
            name='state_message',
            field=models.TextField(blank=True),
        ),
    ]
