# Generated by Django 5.2 on 2025-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_content_state_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plus',
            field=models.BooleanField(default=False),
        ),
    ]
