# Generated by Django 5.2 on 2025-06-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_customuser_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='name',
            field=models.CharField(choices=[('editorial', 'EDITORIAL'), ('homepage', 'HOMEPAGE'), ('omnichannel-campaigns-messages', 'OMNICHANNEL CAMPAINGS:  MESSAGES'), ('omnichannel-campaigns-banners', 'OMNICHANNEL CAMPAINGS:  BANNERS'), ('social-media', 'SOCIAL MEDIA'), ('social-media-payment', 'SOCIAL MEDIA PAYMENT'), ('marketing-campaigns', 'MARKETING CAMPAIGNS'), ('newsletter', 'NEWSLETTER')], max_length=50),
        ),
    ]
