# Generated by Django 5.2 on 2025-07-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_contenttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
