# Generated by Django 5.2 on 2025-07-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_content_schema_historicalcontent_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontent',
            name='schema',
        ),
    ]
