# Generated by Django 5.2 on 2025-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_historicalcontent_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
