# Generated by Django 5.2 on 2025-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_contenttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontent',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
