# Generated by Django 5.2 on 2025-07-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_content_generated_at_content_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontent',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcontent',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='historicalcontent',
            name='state_message',
        ),
    ]
