# Generated by Django 5.2 on 2025-07-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_historicalcontent_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontent',
            name='rejection_message',
        ),
    ]
