# Generated by Django 5.2 on 2025-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_historicalcontent_rejection_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='state_message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llmservice',
            name='multimodal',
            field=models.BooleanField(default=False),
        ),
    ]
