# Generated by Django 5.2 on 2025-07-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_llmmodel_active_llmmodel_state_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='state_message',
            field=models.CharField(blank=True),
        ),
    ]
