# Generated by Django 5.2 on 2025-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_llmmodel_state_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('guest', 'guest'), ('amministratore', 'Amministratore'), ('copywriter', 'Copywriter'), ('approvatore', 'Approvatore'), ('traduttore', 'Traduttore'), ('publisher', 'Publisher')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, to='api.role'),
        ),
    ]
