# Generated by Django 5.2 on 2025-07-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_role_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plus',
        ),
    ]
