# Generated by Django 5.2 on 2025-07-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_customuser_plus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tone_voice',
        ),
        migrations.RemoveField(
            model_name='historicalcontent',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='historicalcontent',
            name='text',
        ),
        migrations.RemoveField(
            model_name='historicalcontent',
            name='tone_voice',
        ),
        migrations.RemoveField(
            model_name='langtranslation',
            name='text',
        ),
    ]
