# Generated by Django 5.2 on 2025-07-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_content_keywords_remove_content_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='language',
            name='country_alpha2',
            field=models.CharField(default='us', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='lang_alpha2',
            field=models.CharField(default='en', max_length=2),
            preserve_default=False,
        ),
    ]
