# Generated by Django 5.2 on 2025-07-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_language_active_language_country_alpha2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='contenttype',
            name='categories',
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('review', 'Review'), ('bozza_rifiutata', 'Bozza Rifiutata'), ('bozza_validata', 'Bozza Validata'), ('review_traduzioni', 'Review Traduzioni'), ('validata', 'Validata'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcontent',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('review', 'Review'), ('bozza_rifiutata', 'Bozza Rifiutata'), ('bozza_validata', 'Bozza Validata'), ('review_traduzioni', 'Review Traduzioni'), ('validata', 'Validata'), ('pubblicata', 'Pubblicata')], default='bozza', max_length=50),
        ),
        migrations.AlterField(
            model_name='langtranslation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validata', 'Validata'), ('rifiutata', 'Rifiutata')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
