# Generated by Django 5.2 on 2025-07-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_content_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='langs',
        ),
    ]
