# Generated by Django 5.2 on 2025-07-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_notify'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notify',
            new_name='Notification',
        ),
    ]
