# Generated by Django 5.2 on 2025-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_notification_created_at_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
