# Generated by Django 5.2 on 2025-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_notification_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='modal_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
