"""add sections to components

Revision ID: 1bc1e61d11ff
Revises: 004
Create Date: 2025-10-28 12:06:57.902810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc1e61d11ff'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_logs_project_id', table_name='activity_logs')
    op.add_column('components', sa.Column('section_key', sa.String(length=100), server_default='default', nullable=False))
    
    # Add section_order allowing NULLs initially
    op.add_column('components', sa.Column('section_order', sa.Integer(), nullable=True))
    
    # Set default value for existing rows
    op.execute('UPDATE components SET section_order = 0')
    
    # Now, alter the column to be NOT NULL
    op.alter_column('components', 'section_order', nullable=False)

    op.create_index(op.f('ix_components_section_key'), 'components', ['section_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_components_section_key'), table_name='components')
    op.drop_column('components', 'section_order')
    op.drop_column('components', 'section_key')
    op.create_index('ix_activity_logs_project_id', 'activity_logs', ['project_id'], unique=False)
    # ### end Alembic commands ###

