services:
 
  uwsgi:
    ports:
      - "8001:8000"
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - uwsgi 

  ai-core:
    # Mount source code for live editing
    volumes:
      - ./ai:/ai-core-app
    working_dir: /ai-core-app
    command: uvicorn server:app --host 0.0.0.0 --port 8081 --workers 1 --log-level warning --reload